### ISSUE TITLE
Data organization

### ISSUE THREAD

**Issue by hongsukchoi** [gbouritsas/Neural3DMM#3]
Hi @gbouritsas. Thanks for your great work.

I wonder how do I get the data described 'Data organization' section of the README.
I don't see any link for download.
Simply running `python data_generation.py --root_dir=/path/to/data_root_dir --dataset=DFAUST --num_valid=100` outputs directory errors.

Bests

**Comment by amituofo1996** [comment]
you could download COMA registration [COMA](https://coma.is.tue.mpg.de/) and download its code [COMA_prepare_data_code](https://github.com/anuragranj/coma)，you could get train.npy and test.npy， and then you can download [FAUST](https://dfaust.is.tue.mpg.de/) then run data_generation code  successfully.
