### ISSUE TITLE
spiral_utils.py issue

### ISSUE THREAD

**Issue by emanuelazcona** [gbouritsas/Neural3DMM#4]
I'm trying the notebook mentioned in the READ_ME on my own dataset of registered meshes. Everything ran smoothly before the generate_spirals() function however.

I keep getting a list index out of range but I followed your instructions on how to organize the data directory with the template and presaved training/testing samples in .NPY format.

**Comment by emanuelazcona** [comment]
Here is a copy of the error thrown.

`IndexError                                Traceback (most recent call last)
<ipython-input-4-de7043dc5b58> in <module>
      6 Adj, Trigs = get_adj_trigs(A, F, shapedata.reference_mesh, meshpackage = shapedata.meshpackage)
      7 
----> 8 spirals_np, spiral_sizes,spirals = generate_spirals(args['step_sizes'], 
      9                                                     M, Adj, Trigs,
     10                                                     reference_points = reference_points,

/Neural3DMM/spiral_utils.py in generate_spirals(step_sizes, M, Adj, Trigs, reference_points, dilation, random, meshpackage, counter_clockwise, nb_stds)
     51             mesh_vertices  = M[i].v
     52 
---> 53         sp = get_spirals(mesh_vertices, Adj[i],Trigs[i],reference_points[i], n_steps=step_sizes[i],\
     54                          padding='zero', counter_clockwise = counter_clockwise, random = random)
     55         Adj_spirals.append(sp)

/Neural3DMM/spiral_utils.py in get_spirals(mesh, adj, trig, reference_points, n_steps, padding, counter_clockwise, random)
    172             cur_t = [t for t in trig_central if t in trig[cur_v]]
    173             if len(ring) == 1:
--> 174                 orientation_0 = (cur_t[0][0]==i and cur_t[0][1]==cur_v) \
    175                                 or (cur_t[0][1]==i and cur_t[0][2]==cur_v) \
    176                                 or (cur_t[0][2]==i and cur_t[0][0]==cur_v)

IndexError: list index out of range`

**Comment by gbouritsas** [comment]
Hi Emanuel, it could be many things. Let's try to narrow it down a bit. Do you get the error when processing the first mesh in the hierarchy, or in a downsampled version (corner cases might emerge after downsampling)? Do you get that in a specific template? Have you tried any other template? Note that this operation has to do only with the template and not with the .npy files.
